package eurekadb;
// Generated Aug 4, 2018 4:58:34 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Texts generated by hbm2java
 */
public class Texts  implements java.io.Serializable {


     private Long id;
     private byte level;
     private String title;
     private Date uploadDate;
     private String text;

    public Texts() {
    }

	
    public Texts(byte level, Date uploadDate, String text) {
        this.level = level;
        this.uploadDate = uploadDate;
        this.text = text;
    }
    
    public Texts(byte level, String title, Date uploadDate, String text) {
       this.level = level;
       this.title = title;
       this.uploadDate = uploadDate;
       this.text = text;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public byte getLevel() {
        return this.level;
    }
    
    public void setLevel(byte level) {
        this.level = level;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public Date getUploadDate() {
        return this.uploadDate;
    }
    
    public void setUploadDate(Date uploadDate) {
        this.uploadDate = uploadDate;
    }
    public String getText() {
        return this.text;
    }
    
    public void setText(String text) {
        this.text = text;
    }




}


