package eurekadb;
// Generated Aug 4, 2018 4:58:34 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Users generated by hbm2java
 */
public class Users  implements java.io.Serializable {


     private Long id;
     private String email;
     private String name;
     private Byte age;
     private String password;
     private Boolean gender;
     private Boolean facebook;
     private Boolean admin;
     private Date signupTime;
     private Date lastLogin;
     private Integer points;

    public Users() {
    }

	
    public Users(String email, String name, String password, Date lastLogin, Integer points) {
        this.email = email;
        this.name = name;
        this.password = password;
        this.lastLogin = lastLogin;
        this.points = points;
    }
    public Users(String email, String name, Byte age, String password, Boolean gender, Boolean facebook, Boolean admin, Date signupTime, Date lastLogin, Integer points) {
       this.email = email;
       this.name = name;
       this.age = age;
       this.password = password;
       this.gender = gender;
       this.facebook = facebook;
       this.admin = admin;
       this.signupTime = signupTime;
       this.lastLogin = lastLogin;
       this.points = points;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Byte getAge() {
        return this.age;
    }
    
    public void setAge(Byte age) {
        this.age = age;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Boolean getGender() {
        return this.gender;
    }
    
    public void setGender(Boolean gender) {
        this.gender = gender;
    }
    public Boolean getFacebook() {
        return this.facebook;
    }
    
    public void setFacebook(Boolean facebook) {
        this.facebook = facebook;
    }
    public Boolean getAdmin() {
        return this.admin;
    }
    
    public void setAdmin(Boolean admin) {
        this.admin = admin;
    }
    public Date getSignupTime() {
        return this.signupTime;
    }
    
    public void setSignupTime(Date signupTime) {
        this.signupTime = signupTime;
    }
    public Date getLastLogin() {
        return this.lastLogin;
    }
    
    public void setLastLogin(Date lastLogin) {
        this.lastLogin = lastLogin;
    }
    public Integer getPoints() {
        return this.points;
    }
    
    public void setPoints(Integer points) {
        this.points = points;
    }




}


